// Bundles the terminal WebView page (design doc §10.2) into one self-contained
// HTML file: xterm.js + the fit addon + the page script inlined with esbuild,
// xterm's stylesheet inlined, and JetBrains Mono embedded as a base64 woff2.
//
// Outputs (both committed):
//   assets/webview/terminal.html            the page, openable in a browser for debugging
//   src/features/terminal/terminalHtml.ts   the same page as a string constant
//
// The app loads the page with `source={{ html }}`; a string constant needs no
// Metro asset plugin and survives every Android file:// / asset:// quirk.
// Run with `pnpm webview:build`.

import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const repo = path.resolve(root, "../..");

const xtermCss = readFileSync(path.join(root, "node_modules/@xterm/xterm/css/xterm.css"), "utf8");
// The desktop's own woff2 (apps/desktop/src/assets/fonts): same family, same
// release, one third the size of the TTF the native side uses.
const fontDir = path.join(repo, "apps/desktop/src/assets/fonts");
const face = (file, weight) => {
  const b64 = readFileSync(path.join(fontDir, file)).toString("base64");
  return `@font-face { font-family: "JetBrains Mono"; font-style: normal; font-weight: ${weight}; src: url(data:font/woff2;base64,${b64}) format("woff2"); }`;
};
const fontFace = [face("JetBrainsMono-Regular.woff2", 400), face("JetBrainsMono-Bold.woff2", 700)].join("\n  ");

const bundle = await build({
  entryPoints: [path.join(root, "webview/terminal/main.ts")],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: ["es2020"],
  minify: true,
  legalComments: "none",
  logLevel: "error",
});
const js = bundle.outputFiles[0].text;
if (js.includes("</script")) throw new Error("bundle contains a script terminator");

const template = readFileSync(path.join(root, "webview/terminal/index.html"), "utf8");
const html = template
  .replace("/*__FONT_FACE__*/", fontFace)
  .replace("/*__XTERM_CSS__*/", xtermCss.replace(/<\/style/g, "<\\/style"))
  .replace("/*__BUNDLE__*/", () => js);

mkdirSync(path.join(root, "assets/webview"), { recursive: true });
writeFileSync(path.join(root, "assets/webview/terminal.html"), html);

const ts = `// GENERATED by scripts/build-webview.mjs — do not edit. Run \`pnpm webview:build\`.
// The terminal WebView page (§10.2) as a string, loaded with \`source={{ html }}\`.
/* eslint-disable */
export const TERMINAL_HTML: string = ${JSON.stringify(html)};
`;
writeFileSync(path.join(root, "src/features/terminal/terminalHtml.ts"), ts);
console.log(`webview: terminal.html ${(html.length / 1024).toFixed(0)} KiB (js ${(js.length / 1024).toFixed(0)} KiB)`);
