// Builds the WebView pages into TypeScript modules the app imports
// (design doc §5 `pnpm webview:build`, §10.2, §10.3).
//
// Each bundle is one exported function with no shared state, so the terminal
// bundle (§10.2) and the Markdown bundle (§10.3) can be written, changed and
// merged independently; `main()` just runs whichever ones exist.
//
// The output is a `.ts` module exporting the whole document as a string, not a
// `.html` asset: the page is handed to `WebView` via `source={{ html }}`, and a
// TypeScript module needs no `metro.config.js` entry, no asset registry and no
// file access at runtime (`allowFileAccess` is off, §10.2).

import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const MOBILE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_DIR = path.join(MOBILE_ROOT, "src", "webview");

/** §10.3: `marked` + `DOMPurify` + the desktop's `renderSafeMarkdown`, inlined. */
export async function buildMarkdownBundle() {
  const source = path.join(MOBILE_ROOT, "webview", "markdown");
  const html = await inlinePage({
    template: path.join(source, "index.html"),
    styles: path.join(source, "styles.css"),
    entry: path.join(source, "entry.ts"),
  });
  return emitModule("markdownBundle.ts", "MARKDOWN_HTML", html, "§10.3 Markdown WebView bundle");
}

const BUNDLES = [buildMarkdownBundle];

async function main() {
  for (const bundle of BUNDLES) {
    const written = await bundle();
    console.log(`webview: ${path.relative(MOBILE_ROOT, written.file)} (${(written.bytes / 1024).toFixed(1)} KiB)`);
  }
}

/** Bundles the entry, minifies the stylesheet, and drops both into the template. */
async function inlinePage({ template, styles, entry }) {
  const bundled = await build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    // The Android System WebView on API 26+; esbuild only has to keep the
    // syntax inside what that engine parses.
    target: ["chrome100"],
    minify: true,
    legalComments: "none",
    write: false,
  });
  const css = await build({
    stdin: { contents: await readFile(styles, "utf8"), loader: "css", resolveDir: path.dirname(styles) },
    minify: true,
    write: false,
  });
  const script = escapeClosingScript(bundled.outputFiles[0].text);
  const page = (await readFile(template, "utf8"))
    .replace("/* STYLES */", () => css.outputFiles[0].text.trim())
    .replace("/* SCRIPT */", () => script);
  const closers = page.match(/<\/script/gi) ?? [];
  if (closers.length !== 1) throw new Error(`inlined page has ${closers.length} </script> tokens, expected 1`);
  return page;
}

/**
 * `</script` inside the bundled JavaScript would close the tag it lives in. It
 * only ever occurs inside string literals and regular expressions, where the
 * escape is a no-op for the parser.
 */
function escapeClosingScript(script) {
  return script.replace(/<\/(script)/gi, "<\\/$1");
}

async function emitModule(name, constant, html, provenance) {
  await mkdir(GENERATED_DIR, { recursive: true });
  const file = path.join(GENERATED_DIR, name);
  const contents = [
    "// GENERATED by scripts/build-webview.mjs — do not edit.",
    `// ${provenance}. Rebuild with \`pnpm --filter @muxflow/mobile webview:build\`.`,
    "",
    `export const ${constant} = ${JSON.stringify(html)};`,
    "",
  ].join("\n");
  await writeFile(file, contents, "utf8");
  return { file, bytes: Buffer.byteLength(contents) };
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
