// Builds the WebView pages into TypeScript modules the app imports
// (design doc §5 `pnpm webview:build`, §10.2, §10.3).
//
// Each bundle is one exported function with no shared state, so the terminal
// bundle (§10.2) and the Markdown bundle (§10.3) can be written, changed and
// merged independently; `main()` just runs whichever ones exist.
//
// The output is a `.ts` module exporting the whole document as a string, not a
// `.html` asset: the page is handed to `WebView` via `source={{ html }}`, and a
// TypeScript module needs no `metro.config.js` entry, no asset registry and no
// file access at runtime (`allowFileAccess` is off, §10.2).

import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const MOBILE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_DIR = path.join(MOBILE_ROOT, "src", "webview");

/** §10.3: `marked` + `DOMPurify` + the desktop's `renderSafeMarkdown`, inlined. */
export async function buildMarkdownBundle() {
  const source = path.join(MOBILE_ROOT, "webview", "markdown");
  const html = await inlinePage({
    template: path.join(source, "index.html"),
    styles: path.join(source, "styles.css"),
    entry: path.join(source, "entry.ts"),
  });
  return emitModule("markdownBundle.ts", "MARKDOWN_HTML", html, "§10.3 Markdown WebView bundle");
}

/** §10.2: xterm.js + fit addon + the page script, xterm's stylesheet and JetBrains Mono (woff2, base64) inlined. */
export async function buildTerminalBundle() {
  const repo = path.resolve(MOBILE_ROOT, "../..");
  const xtermCss = await readFile(path.join(MOBILE_ROOT, "node_modules/@xterm/xterm/css/xterm.css"), "utf8");
  // The desktop's own woff2 (apps/desktop/src/assets/fonts): same family, same release.
  const fontDir = path.join(repo, "apps/desktop/src/assets/fonts");
  const face = async (file, weight) => {
    const b64 = (await readFile(path.join(fontDir, file))).toString("base64");
    return `@font-face { font-family: "JetBrains Mono"; font-style: normal; font-weight: ${weight}; src: url(data:font/woff2;base64,${b64}) format("woff2"); }`;
  };
  const fontFace = [await face("JetBrainsMono-Regular.woff2", 400), await face("JetBrainsMono-Bold.woff2", 700)].join("\n  ");
  const bundled = await build({
    entryPoints: [path.join(MOBILE_ROOT, "webview/terminal/main.ts")],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: ["es2020"],
    minify: true,
    legalComments: "none",
    logLevel: "error",
  });
  const js = bundled.outputFiles[0].text;
  if (js.includes("</script")) throw new Error("terminal bundle contains a script terminator");
  const template = await readFile(path.join(MOBILE_ROOT, "webview/terminal/index.html"), "utf8");
  const html = template
    .replace("/*__FONT_FACE__*/", fontFace)
    .replace("/*__XTERM_CSS__*/", xtermCss.replace(/<\/style/g, "<\\/style"))
    .replace("/*__BUNDLE__*/", () => js);
  // Also written as a plain .html so it can be opened in a browser for debugging.
  await mkdir(path.join(MOBILE_ROOT, "assets/webview"), { recursive: true });
  await writeFile(path.join(MOBILE_ROOT, "assets/webview/terminal.html"), html);
  const file = path.join(MOBILE_ROOT, "src/features/terminal/terminalHtml.ts");
  const ts = `// GENERATED by scripts/build-webview.mjs — do not edit. Run \`pnpm webview:build\`.
// The terminal WebView page (§10.2) as a string, loaded with \`source={{ html }}\`.
/* eslint-disable */
export const TERMINAL_HTML: string = ${JSON.stringify(html)};
`;
  await writeFile(file, ts);
  return { file, bytes: Buffer.byteLength(ts) };
}

const BUNDLES = [buildMarkdownBundle, buildTerminalBundle];

async function main() {
  for (const bundle of BUNDLES) {
    const written = await bundle();
    console.log(`webview: ${path.relative(MOBILE_ROOT, written.file)} (${(written.bytes / 1024).toFixed(1)} KiB)`);
  }
}

/** Bundles the entry, minifies the stylesheet, and drops both into the template. */
async function inlinePage({ template, styles, entry }) {
  const bundled = await build({
    entryPoints: [entry],
    bundle: true,
    format: "iife",
    // The Android System WebView on API 26+; esbuild only has to keep the
    // syntax inside what that engine parses.
    target: ["chrome100"],
    minify: true,
    legalComments: "none",
    write: false,
  });
  const css = await build({
    stdin: { contents: await readFile(styles, "utf8"), loader: "css", resolveDir: path.dirname(styles) },
    minify: true,
    write: false,
  });
  const script = escapeClosingScript(bundled.outputFiles[0].text);
  const page = (await readFile(template, "utf8"))
    .replace("/* STYLES */", () => css.outputFiles[0].text.trim())
    .replace("/* SCRIPT */", () => script);
  const closers = page.match(/<\/script/gi) ?? [];
  if (closers.length !== 1) throw new Error(`inlined page has ${closers.length} </script> tokens, expected 1`);
  return page;
}

/**
 * `</script` inside the bundled JavaScript would close the tag it lives in. It
 * only ever occurs inside string literals and regular expressions, where the
 * escape is a no-op for the parser.
 */
function escapeClosingScript(script) {
  return script.replace(/<\/(script)/gi, "<\\/$1");
}

async function emitModule(name, constant, html, provenance) {
  await mkdir(GENERATED_DIR, { recursive: true });
  const file = path.join(GENERATED_DIR, name);
  const contents = [
    "// GENERATED by scripts/build-webview.mjs — do not edit.",
    `// ${provenance}. Rebuild with \`pnpm --filter @muxflow/mobile webview:build\`.`,
    "",
    `export const ${constant} = ${JSON.stringify(html)};`,
    "",
  ].join("\n");
  await writeFile(file, contents, "utf8");
  return { file, bytes: Buffer.byteLength(contents) };
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
