// Signs the release APK with Muxflow's own key instead of the template's
// public debug keystore.
//
// `android/` is regenerated by `expo prebuild`, so the signing config has to
// be injected here rather than edited in build.gradle. The key material itself
// never reaches the generated project: Gradle reads it from the environment at
// build time.
//
//   MUXFLOW_ANDROID_KEYSTORE           path to the .jks/.keystore file
//   MUXFLOW_ANDROID_KEYSTORE_PASSWORD
//   MUXFLOW_ANDROID_KEY_ALIAS
//   MUXFLOW_ANDROID_KEY_PASSWORD
//
// A release task with any of them unset fails the build. There is no fallback
// to the debug key: a debug-signed "release" is exactly what this prevents.
// Debug builds are unchanged.
const { withAppBuildGradle } = require("expo/config-plugins");

const RELEASE_SIGNING_CONFIG = `
        release {
            def keystore = System.getenv('MUXFLOW_ANDROID_KEYSTORE')
            if (keystore) {
                storeFile file(keystore)
                storePassword System.getenv('MUXFLOW_ANDROID_KEYSTORE_PASSWORD')
                keyAlias System.getenv('MUXFLOW_ANDROID_KEY_ALIAS')
                keyPassword System.getenv('MUXFLOW_ANDROID_KEY_PASSWORD')
            }
        }`;

const RELEASE_KEY_GUARD = `
// Injected by plugins/withReleaseSigning.js.
gradle.taskGraph.whenReady { graph ->
    def buildsRelease = graph.allTasks.any { it.project.name == 'app' && it.name.contains('Release') }
    def required = [
        'MUXFLOW_ANDROID_KEYSTORE',
        'MUXFLOW_ANDROID_KEYSTORE_PASSWORD',
        'MUXFLOW_ANDROID_KEY_ALIAS',
        'MUXFLOW_ANDROID_KEY_PASSWORD',
    ]
    def missing = required.findAll { !System.getenv(it) }
    if (buildsRelease && !missing.isEmpty()) {
        throw new GradleException("Release builds are signed with the Muxflow release key; set \${missing.join(', ')}. See docs/mobile/toolchain.md.")
    }
}
`;

function applyReleaseSigning(gradle) {
  if (gradle.includes("MUXFLOW_ANDROID_KEYSTORE")) return gradle;

  const withConfig = gradle.replace(/signingConfigs \{/, (match) => match + RELEASE_SIGNING_CONFIG);
  // The template's release build type: `release {`, its "Caution!" comments,
  // then `signingConfig signingConfigs.debug`.
  const withBuildType = withConfig.replace(
    /(buildTypes \{[\s\S]*?release \{\s*\n)((?:\s*\/\/.*\n)*)(\s*)signingConfig signingConfigs\.debug/,
    "$1$3signingConfig signingConfigs.release",
  );
  if (withConfig === gradle || withBuildType === withConfig) {
    // The template moved. Failing prebuild beats silently shipping the debug key.
    throw new Error("withReleaseSigning: app/build.gradle no longer matches the expected template");
  }
  return withBuildType + RELEASE_KEY_GUARD;
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.language !== "groovy") {
      throw new Error("withReleaseSigning: expected a Groovy app/build.gradle");
    }
    mod.modResults.contents = applyReleaseSigning(mod.modResults.contents);
    return mod;
  });
};

module.exports.applyReleaseSigning = applyReleaseSigning;
